### ISSUE TITLE
Type issues arising due to combining datasets with eager

### ISSUE THREAD

**Issue by skeydan** [rstudio/tfdatasets#12]
Hi JJ,

picking up on the snippet we discussed ... I've extracted a small example we could experiment with.

As I see it, the difficulty is that all works the way you suggested when executed in the global env, but not (not in the same way, that is) when called via datasets.
When called from datasets, tensors inside the `load_image` function are not eager, e.g., they don't have a $numpy() and seem to come across as environments (see experimental code lines below).

This here is related I think:

https://github.com/tensorflow/tensorflow/issues/14732

```
library(keras)
use_implementation("tensorflow")

library(tensorflow)
tfe_enable_eager_execution(device_policy = "silent")

library(tfdatasets)

system("wget https://blogs.rstudio.com/tensorflow/posts/2018-09-10-eager-style-transfer/images/style_epoch_1000.png")



# Without datasets --------------------------------------------------------

image <-  tf$read_file("style_epoch_1000.png")
image <- tf$image$decode_jpeg(image)
w <- k_shape(image)[2] 
w
# we don't need this
# w <- as.integer(w)

w2 <- as.integer(w / 2L)
# but here, we need the as.integer
# this does not work
# cannot compute StridedSlice as input #2(zero-based) was expected to be a int32 tensor but is a double tensor
# w2 <- w / 2L
w2
real_image <- image[ , 1L:w2, ]
input_image <- image[ , (w2 + 1L):w, ]

list(input_image, real_image)



# with datasets -----------------------------------------------------------


load_image <- function(image_file) {
  
  image <- tf$image$decode_jpeg(image_file)
  
  w <- k_shape(image)[2] 
  # can't use as.integer on this
  # cannot coerce type 'environment' to vector of type 'integer'.
  # w <- as.integer(w)
  
  # after division the TF type will be float64
  # so we need
  w2 <- (w / 2L) %>% k_cast(tf$int32)
  # w2 <- as.integer(w / 2L)
  # w2 <- w / 2L
  real_image <- image[ , 1L:w2, ]
  input_image <- image[ , (w2 + 1L):w, ]
  
  list(input_image, real_image)
  
}

train_dataset <-
  tf$data$Dataset$list_files("style_epoch_1000.png") %>%
  dataset_map(function(x) load_image(x)) %>%
  dataset_batch(1)


```

**Comment by jjallaire** [comment]
What about using `tfe.py_func()` as suggested in the TF issue? https://www.tensorflow.org/api_docs/python/tf/contrib/eager/py_func

**Comment by skeydan** [comment]
Thanks ... I need to go one step back (too few session restarts last night).

First, without datasets, this is the correct code resulting in no warnings, and having both `w` and `w2` being R integers instead of eager tensors.
(Lesson for me being: Even if it's possible to get things done with eager tensors now, it's still a sensible thing to convert to R types).

```
# Without datasets --------------------------------------------------------

image <-  tf$read_file("style_epoch_1000.png")
image <- tf$image$decode_png(image)
w <- as.integer(k_shape(image)[2])
w

w2 <- as.integer(w / 2L)
w2
real_image <- image[ , 1L:w2, ]
input_image <- image[ , (w2 + 1L):w, ]

list(input_image, real_image)

```

**Comment by skeydan** [comment]
Now for `py_func`...

I've been using `tf$py_func` here 

https://github.com/rstudio/keras/blob/4d2cbc497f06c1c286b7b4545cd6a15f5d67fe01/vignettes/examples/eager_image_captioning.R

already because in that case, I didn't see another way (whereas in the current case, it is about getting rid of the warning, or rather, the cause thereof).

Now, I am testing both `tf$contrib$eager$py_func` and `tf$py_func` in the below code.

For the true use case, I need to take a boolean argument and then, condition on it, so now the test code has been adapted for that.

While the `contrib` version errors with

```
	 [[{{node EagerPyFunc}} = EagerPyFunc[Tin=[DT_STRING, DT_BOOL], Tout=[DT_UINT8, DT_UINT8], token="pyfunc_2"](arg0, Const)]]
Error: UnknownError: RuntimeError: Evaluation error: argument is not interpretable as logical.
```

with `py_func` it works, and I get rid of the warning.

The comparison made in

https://www.tensorflow.org/api_docs/python/tf/contrib/eager/py_func

> tf.contrib.eager.py_func is similar in spirit to tf.py_func, but unlike the latter, the former lets you use TensorFlow operations in the wrapped Python function. In particular, while tf.py_func only runs on CPUs and wraps functions that take NumPy arrays as inputs and return NumPy arrays as outputs, tf.contrib.eager.py_func can be placed on GPUs and wraps functions that take Tensors as inputs, execute TensorFlow operations in their bodies, and return Tensors as outputs.

does not seem totally up-to-date and/or correct (e.g., I can use it on GPU).
I think I would stay with `tf$py_func$`. Also it's probable that all eager related functionality will move out of contrib I guess...

Then in principle, I think this should be a candidate for a wrapper? 
If so, I'd say we might create it around the non-contrib function...

```
# with datasets -----------------------------------------------------------


load_image <- function(image_file, is_train) {
  
  image <- tf$read_file(image_file)
  image <- tf$image$decode_png(image)
  
  w <- as.integer(k_shape(image)[2])
  w2 <- as.integer(w / 2L)
  if(is_train) {
    real_image <- image[ , 1L:w2, ]
    input_image <- image[ , (w2 + 1L):w, ]
  } else {
    real_image <- image[ , 1L:w2, ]
    input_image <- image[ , (w2 + 1L):w, ]
  }
 
  list(input_image, real_image)
  
}

train_dataset <-
  tf$data$Dataset$list_files("style_epoch_1000.png") %>%
  dataset_map(function(image)
    tf$py_func(load_image, list(image, tf$constant(TRUE, dtype = tf$bool)), list(tf$uint8, tf$uint8))) %>%
    #tf$contrib$eager$py_func(load_image, list(image, tf$constant(TRUE, dtype = tf$bool)), list(tf$uint8, tf$uint8))) %>%
  dataset_batch(1)

iter <- make_iterator_one_shot(train_dataset)

until_out_of_range({
  batch <- iterator_get_next(iter)
  input_image <- batch[[1]]
  target <- batch[[2]]
  print(input_image$shape)
  print(target$shape)
})

```

**Comment by jjallaire** [comment]
Yeah, we should definitely have a wrapper for py_func. How about `tf_r_func()` ?

My one question though about py_func is whether it's going to ever run the function on a background thread (if so we need to make some special provisions from R)
