### ISSUE TITLE
Cannot use function in "x" argument to dataset_prepare()

### ISSUE THREAD

**Issue by vankesteren** [rstudio/tfdatasets#24]
I am using a function (e.g.,  `colnames(dat)`) as the `x` argument to `dataset_prepare`:

```r
library(tfdatasets)

dat     <- mtcars[,5:7]
tmp_loc <- tempfile("tfdata_")

write.csv(dat, file = tmp_loc, row.names = FALSE)

dat_spec <- csv_record_spec(tmp_loc)
tf_dat   <- text_line_dataset(tmp_loc, record_spec = dat_spec)
tf_dat   <- dataset_prepare(tf_dat, x = colnames(dat))
```

The following error occurs:
`Error: could not find function "colnames"`

Quasiquotation fixes this issue
```r
tf_dat     <- dataset_prepare(tf_dat, x = !!colnames(dat))
```

but introduces another unwanted error:
```
Warning message:
The `parent` argument of `as_data_mask()` is deprecated.
The parent of the data mask is determined from either:

  * The `env` argument of `eval_tidy()`
  * Quosure environments when applicable
This warning is displayed once per session. 
```

**Comment by skeydan** [comment]
Hi, I agree this is not ideal, but the latter message is just a warning, I wonder if you can live with this until this has been discussed?

**Comment by dfalbel** [comment]
This is fixed with https://github.com/rstudio/tfdatasets/pull/34/commits/36746a6636799409489f2259642e27134d106d65

Also added some tests here https://github.com/rstudio/tfdatasets/pull/34/commits/af7231fe977b027e966a6a5738dc2e9da1b16729 too

**Comment by vankesteren** [comment]
Thanks!
