### ISSUE TITLE
view metrics = TRUE crashes rstudio Rsession if training with a dataset

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/tfdatasets#4]

**Comment by jjallaire** [comment]
Could you provide a bit more detail? Perhaps the exact call which causes the crash or ideally the entire code snippet (or an equivalent snippet).

**Comment by t-kalinowski** [comment]
So, I fixed the issue while trying to make a minimal example (let that be a lesson to me!)

I had been using `tf$bitcast` on a batched dataset of `FixedLengthRecordDataset`, and I hadn't realized that the shape after batching was `(batchsize, ?)`. bitcasting discarded the shape information (which was fine for my application), but for some reason this particular transformation was making Rstudio crash when viewing metrics. 
The issue was resolved when I explicitly called `set_shape()` before bitcasting and after batching. 

Unfortunately, I wasn't able to reproduce the issues in a minimal example I could share.
