### ISSUE TITLE
Error passing dataset to keras fit

### ISSUE THREAD

**Issue by skeydan** [rstudio/tfdatasets#9]
The following (or rather, it's equivalent) works in Python

```
library(keras)
use_implementation("keras")
keras:::is_tensorflow_implementation()

model <- keras_model_sequential()
# Adds a densely-connected layer with 64 units to the model:
model %>% layer_dense(units = 64, activation='relu', input_shape = c(32))
# Add another:
model %>% layer_dense(units = 64, activation='relu')
# Add a softmax layer with 10 output units:
model %>% layer_dense(units = 10, activation='softmax')

model %>% compile(optimizer = 'adam',
                  loss = 'categorical_crossentropy',
                  metrics = list('accuracy'))

model %>% summary()

data <- matrix(rnorm(1000 * 32), nrow = 1000, ncol = 32)
labels <- matrix(rnorm(1000 * 10), nrow = 1000, ncol = 10)

library(tfdatasets)
# Instantiates a toy dataset instance:
dataset <- tensor_slices_dataset(reticulate::tuple(data, labels)) %>% 
  dataset_batch(32) %>%
  dataset_repeat()
dataset
# Don't forget to specify `steps_per_epoch` when calling `fit` on a dataset.
model %>% fit(dataset, epochs = 10, steps_per_epoch = 30)
```

but causes

```
> model %>% fit(dataset, epochs = 10, steps_per_epoch = 30)
 Hide Traceback
 
 Rerun with Debug
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: When feeding symbolic tensors to a model, we expect thetensors to have a static batch size. Got tensor with shape: (None, 32) 
16.
stop(structure(list(message = "ValueError: When feeding symbolic tensors to a model, we expect thetensors to have a static batch size. Got tensor with shape: (None, 32)", 
    call = py_call_impl(callable, dots$args, dots$keywords), 
    cppstack = structure(list(file = "", line = -1L, stack = c("/home/key/R/x86_64-redhat-linux-gnu-library/3.5/reticulate/libs/reticulate.so(Rcpp::exception::exception(char const*, bool)+0x78) [0x7f3ca4b05098]", 
    "/home/key/R/x86_64-redhat-linux-gnu-library/3.5/reticulate/libs/reticulate.so(Rcpp::stop(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x2b) [0x7f3ca4b0521b]",  ... 
15.
standardize_single_array at training_utils.py#23
14.
standardize_input_data at training_utils.py#90
13.
_standardize_user_data at training.py#754
12.
fit at training.py#955
11.
(structure(function (...) 
{
    dots <- py_resolve_dots(list(...))
    result <- py_call_impl(callable, dots$args, dots$keywords) ... 
10.
do.call(object$fit, args) 
9.
fit(., dataset, epochs = 10, steps_per_epoch = 30) 
8.
function_list[[k]](value) 
7.
withVisible(function_list[[k]](value)) 
6.
freduce(value, `_function_list`) 
5.
`_fseq`(`_lhs`) 
4.
eval(quote(`_fseq`(`_lhs`)), env, env) 
3.
eval(quote(`_fseq`(`_lhs`)), env, env) 
2.
withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
1.
model %>% fit(dataset, epochs = 10, steps_per_epoch = 30) 

> 
```

for me.

I was checking the test `dataset_prepare can provide keras input tensors"`for reference but that works pretty differently (getting batches). But the vignette suggests I could pass the dataset like that if I'm correct.

**Comment by jjallaire** [comment]
I recall seeing this error before and I can't for the life of me recall what the workaround is/was....

Oh, now I remember, you need to add `drop_reminainer` to the call to `dataset_batch()`. We originally did this by default:

https://github.com/rstudio/tfdatasets/commit/a72254e25043fac424774495e09bd7cba3078097

But this broke some people so: 

https://github.com/rstudio/tfdatasets/commit/1961fbbc17b871b8635e7490d6d089a8466d3f56

**Comment by skeydan** [comment]
Oh, in a way this:

> When feeding symbolic tensors to a model, we expect thetensors to have a static batch size. Got tensor with shape: (None, 32) 

can be understood like this... Interestingly this is even required if the dataset is evenly divisible by the batchsize ...?

On the same topic of staticly specified shapes, there is something else I had to add to the R version to make it run: the input_shape.

The equivalent Python

```
model = keras.Sequential()
# Adds a densely-connected layer with 64 units to the model:
model.add(keras.layers.Dense(64, activation='relu'))
```

runs without...

**Comment by skeydan** [comment]
BTW I need to be more careful with my versions. Even though I'm reinstalling from github so frequently I had a version now where `dataset_batch` did not even have the `drop_remainder`parameter...

**Comment by jjallaire** [comment]
I am now curious as to whether there is a Python example with Keras and TF datasets that does not use `batch_and_drop_remainder()` (and if so whether/how that actually works). Here's a datasets example I found that does use `batch_and_drop_remainder()`: https://github.com/tensorflow/tpu/blob/master/models/experimental/cifar_keras/cifar_keras.py

**Comment by skeydan** [comment]
yes, it seems to work in Python... if I take the failing code from 
https://github.com/skeydan/tf_docs_R/issues/1 
and add an input_shape (but use simple `batch()`,  not `batch_and_drop_remainder()`) it runs fine:

(The corresponding R code - that needs  `batch_and_drop_remainder()` - has `input_shape` already because that was needed for another reason already)

```
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential()
# Adds a densely-connected layer with 64 units to the model:
model.add(keras.layers.Dense(64, activation='relu', input_shape = (32,)))
# Add another:
model.add(keras.layers.Dense(64, activation='relu'))
# Add a softmax layer with 10 output units:
model.add(keras.layers.Dense(10, activation='softmax'))

model.compile(optimizer=tf.train.AdamOptimizer(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

import numpy as np

data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

#model.fit(data, labels, epochs=10, batch_size=32)
          
dataset = tf.data.Dataset.from_tensor_slices((data, labels))
dataset
dataset = dataset.batch(32)
dataset = dataset.repeat()
dataset
# Don't forget to specify `steps_per_epoch` when calling `fit` on a dataset.
model.fit(dataset, epochs=10, steps_per_epoch=30)
```

**Comment by jjallaire** [comment]
So I wonder if it would be better for us document the use of `input_shape` (as opposed to `drop_remainder`) as a requirement for keras + tf datasets?

**Comment by jjallaire** [comment]
Actually, if I modify the Keras example here (https://github.com/rstudio/tfdatasets/blob/master/vignettes/introduction.Rmd) to pass an input_shape in the first layer and to exclude the drop_remainder argument from dataset_batch() I still get the error (so it seems like we should definitely document drop_remainder as a requirement)

**Comment by skeydan** [comment]
Yes - sorry if I was unclear - that is what I meant

**Comment by skeydan** [comment]
Overall the current state is I think

- `input_shape` is needed when fitting datasets with Keras in both R and Python (although errors differ when testing "equivalent"  versions)
- `batch_and_drop_remainder` is needed from R only (so the above question 

> how that actually works

is still open...)

**Comment by skeydan** [comment]
thought I had an idea but didn't help
Anyway looking at the traceback for R (not using `batch_and_drop_remainder`) I see it fails checking

```
def standardize_single_array(x):
    if x is None:
        return None
    elif K.is_tensor(x):
        shape = K.int_shape(x)
        if shape is None or shape[0] is None:
            raise ValueError(
                'When feeding symbolic tensors to a model, we expect the'
                'tensors to have a static batch size. '
                'Got tensor with shape: %s' % str(shape))
        return x
    elif x.ndim == 1:
        x = np.expand_dims(x, 1)
    return x
```

and assuming this same path gets called in both R and Python versions, and seeing that in both cases the dataset is 

```
<RepeatDataset shapes: ((?, 32), (?, 10)), types: (tf.float64, tf.float64)>

```

I wonder how it ever works...

**Comment by skeydan** [comment]
Not an answer to your question (will follow) but ... just found that when using datasets with estimators you don't need it batch_and_drop_remainder...

```
library(keras)
use_implementation("tensorflow")
model <- keras_model_sequential()
model %>% layer_dense(units = 16, activation = 'relu', input_shape = 10)
model %>% layer_dense(units = 1, activation = 'sigmoid')

model %>% compile(loss = 'binary_crossentropy', optimizer = 'adam')
model %>% summary()

library(tfdatasets)
input_fn <- function() {
  x <- matrix(rnorm(1024 * 10), nrow = 1024, ncol = 10)
  y <- matrix(sample(0:1, 1024, replace = TRUE), nrow = 1024)
  dataset <- tensor_slices_dataset(tuple(x, y)) %>%
    dataset_repeat(10) %>%
    dataset_batch(32)
  dataset
}

library(tfestimators)
estimator <- keras_model_to_estimator(
  keras_model = model)

estimator %>% train(input_fn = input_fn, steps = 10)
```

**Comment by skeydan** [comment]
Minimal example:

```
import tensorflow as tf
from tensorflow import keras
import numpy as np

model = keras.Sequential()
model.add(keras.layers.Dense(1, activation='relu', input_shape = (8,)))
model.compile(optimizer=tf.train.AdamOptimizer(0.001), loss='mse')

data = np.random.random((100, 8))
labels = np.random.random((100, 1))
dataset = tf.data.Dataset.from_tensor_slices((data, labels))
dataset = dataset.batch(32)
model.fit(dataset, epochs=1, steps_per_epoch = 3)
```

```
library(keras)
library(tfdatasets)

model <- keras_model_sequential()
model %>% layer_dense(units = 1, activation='relu', input_shape = 8)
model %>% compile(optimizer = "adam", loss='mse')

data <- matrix(rnorm(100*8), ncol=8)
labels <- matrix(rnorm(100*1), ncol=1)
dataset <- tensor_slices_dataset(tuple(data, labels)) %>%
  #  dataset_batch(32, drop_remainder = TRUE)
  dataset_batch(32)
model %>% fit(dataset, epochs=1, steps_per_epoch = 3)

#   ValueError: When feeding symbolic tensors to a model, we expect thetensors
#   to have a static batch size. Got tensor with shape: (None, 8)
```

**Comment by jjallaire** [comment]
It turns out that the difference here is the implementation. If we revise our code use the tensorflow implementation then all works the same in R:

```r
library(keras)
use_implementation("tensorflow")

library(tfdatasets)

model <- keras_model_sequential()
model %>% layer_dense(units = 1, activation='relu', input_shape = 8)
model %>% compile(optimizer = "adam", loss='mse')

data <- matrix(rnorm(100*8), ncol=8)
labels <- matrix(rnorm(100*1), ncol=1)
dataset <- tensor_slices_dataset(list(data, labels)) %>%
  #  dataset_batch(32, drop_remainder = TRUE)
  dataset_batch(32)

model %>% fit(dataset, epochs=1, steps_per_epoch = 3)
```

**Comment by skeydan** [comment]
oh, really!! I thought I'd tested that (as I've tested quite some things in both implementations now...)
But at least now we know :-)

**Comment by skeydan** [comment]
Landed on https://www.tensorflow.org/api_docs/python/tf/contrib/data/batch_and_drop_remainder and I think I finally understood something that should probably have been clear before ;-))


> Like tf.data.Dataset.batch, this transformation combines consecutive elements of this dataset into batches. However, if the batch size does not evenly divide the input dataset size, this transformation will drop the final smaller element.

> The following example illustrates the difference between this transformation and Dataset.batch():

```
dataset = tf.data.Dataset.range(200)
batched = dataset.apply(tf.contrib.data.batch_and_drop_remainder(128))
print(batched.output_shapes)  # ==> "(128,)" (the batch dimension is known)
```

> By contrast, dataset.batch(128) would yield a two-element dataset with shapes (128,) and (72,), so the batch dimension would not be statically known.

So this finally made it clear to me that the TF user is free to choose whether she wants all batches to be the same size, or is ok with one possibly being smaller than the others (both should work but it's my choice).
So together with you saying the above things work with TF implementation but not Keras, there must be something about Keras impl that requires a static batch size. 

 (I've never investigated this but I think that also some models (LSTM) require dataset size to be evenly divisible by batch size - while other models don't (I think))
